version: '1'
services:
  postgres:
    image: postgres:15.1
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env

  nestjs-api:
    image: nestjs-api
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge