version: '3'
services:
  postgres:
    image: postgres:15.1
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env

  backend:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
